### ISSUE TITLE
while launching gazebo file

### ISSUE THREAD

**Issue by EhrazImam** [mzahana/px4_fast_planner#35]
... logging to /home/enord/.ros/log/85e76976-3346-11ec-96d8-706655b11773/roslaunch-enord-32093.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.177.94:36487/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /fast_planner_node/bspline/limit_acc: 2.0
 * /fast_planner_node/bspline/limit_ratio: 1.1
 * /fast_planner_node/bspline/limit_vel: 3.0
 * /fast_planner_node/fsm/flight_type: 1
 * /fast_planner_node/fsm/thresh_no_replan: 2.0
 * /fast_planner_node/fsm/thresh_replan: 1.5
 * /fast_planner_node/fsm/waypoint0_x: 19.0
 * /fast_planner_node/fsm/waypoint0_y: 0.0
 * /fast_planner_node/fsm/waypoint0_z: 1.0
 * /fast_planner_node/fsm/waypoint1_x: -19.0
 * /fast_planner_node/fsm/waypoint1_y: 0.0
 * /fast_planner_node/fsm/waypoint1_z: 1.0
 * /fast_planner_node/fsm/waypoint2_x: 0.0
 * /fast_planner_node/fsm/waypoint2_y: 19.0
 * /fast_planner_node/fsm/waypoint2_z: 1.0
 * /fast_planner_node/fsm/waypoint_num: 2
 * /fast_planner_node/manager/clearance_threshold: 0.2
 * /fast_planner_node/manager/control_points_distance: 0.5
 * /fast_planner_node/manager/dynamic_environment: 0
 * /fast_planner_node/manager/local_segment_length: 6.0
 * /fast_planner_node/manager/max_acc: 2.0
 * /fast_planner_node/manager/max_jerk: 4.0
 * /fast_planner_node/manager/max_vel: 3.0
 * /fast_planner_node/manager/use_geometric_path: False
 * /fast_planner_node/manager/use_kinodynamic_path: True
 * /fast_planner_node/manager/use_optimization: True
 * /fast_planner_node/manager/use_topo_path: False
 * /fast_planner_node/optimization/algorithm1: 15
 * /fast_planner_node/optimization/algorithm2: 11
 * /fast_planner_node/optimization/dist0: 0.4
 * /fast_planner_node/optimization/lambda1: 10.0
 * /fast_planner_node/optimization/lambda2: 5.0
 * /fast_planner_node/optimization/lambda3: 1e-05
 * /fast_planner_node/optimization/lambda4: 0.01
 * /fast_planner_node/optimization/lambda7: 100.0
 * /fast_planner_node/optimization/max_acc: 2.0
 * /fast_planner_node/optimization/max_iteration_num1: 2
 * /fast_planner_node/optimization/max_iteration_num2: 300
 * /fast_planner_node/optimization/max_iteration_num3: 200
 * /fast_planner_node/optimization/max_iteration_num4: 200
 * /fast_planner_node/optimization/max_iteration_time1: 0.0001
 * /fast_planner_node/optimization/max_iteration_time2: 0.005
 * /fast_planner_node/optimization/max_iteration_time3: 0.003
 * /fast_planner_node/optimization/max_iteration_time4: 0.003
 * /fast_planner_node/optimization/max_vel: 3.0
 * /fast_planner_node/optimization/order: 3
 * /fast_planner_node/planner_node/planner: 1
 * /fast_planner_node/sdf_map/cx: 321.046386719
 * /fast_planner_node/sdf_map/cy: 243.449691772
 * /fast_planner_node/sdf_map/depth_filter_margin: 2
 * /fast_planner_node/sdf_map/depth_filter_maxdist: 5.0
 * /fast_planner_node/sdf_map/depth_filter_mindist: 0.2
 * /fast_planner_node/sdf_map/depth_filter_tolerance: 0.15
 * /fast_planner_node/sdf_map/esdf_slice_height: 0.3
 * /fast_planner_node/sdf_map/frame_id: map
 * /fast_planner_node/sdf_map/fx: 387.229248047
 * /fast_planner_node/sdf_map/fy: 387.229248047
 * /fast_planner_node/sdf_map/ground_height: -1.0
 * /fast_planner_node/sdf_map/k_depth_scaling_factor: 1000.0
 * /fast_planner_node/sdf_map/local_bound_inflate: 0.0
 * /fast_planner_node/sdf_map/local_map_margin: 50
 * /fast_planner_node/sdf_map/local_update_range_x: 5.5
 * /fast_planner_node/sdf_map/local_update_range_y: 5.5
 * /fast_planner_node/sdf_map/local_update_range_z: 4.5
 * /fast_planner_node/sdf_map/map_size_x: 40.0
 * /fast_planner_node/sdf_map/map_size_y: 20.0
 * /fast_planner_node/sdf_map/map_size_z: 5.0
 * /fast_planner_node/sdf_map/max_ray_length: 4.5
 * /fast_planner_node/sdf_map/min_ray_length: 0.5
 * /fast_planner_node/sdf_map/obstacles_inflation: 0.099
 * /fast_planner_node/sdf_map/p_hit: 0.65
 * /fast_planner_node/sdf_map/p_max: 0.9
 * /fast_planner_node/sdf_map/p_min: 0.12
 * /fast_planner_node/sdf_map/p_miss: 0.35
 * /fast_planner_node/sdf_map/p_occ: 0.8
 * /fast_planner_node/sdf_map/pose_type: 1
 * /fast_planner_node/sdf_map/resolution: 0.1
 * /fast_planner_node/sdf_map/show_esdf_time: False
 * /fast_planner_node/sdf_map/show_occ_time: False
 * /fast_planner_node/sdf_map/skip_pixel: 2
 * /fast_planner_node/sdf_map/use_depth_filter: True
 * /fast_planner_node/sdf_map/virtual_ceil_height: 2.5
 * /fast_planner_node/sdf_map/visualization_truncate_height: 2.49
 * /fast_planner_node/search/allocate_num: 100000
 * /fast_planner_node/search/check_num: 5
 * /fast_planner_node/search/horizon: 7.0
 * /fast_planner_node/search/init_max_tau: 0.8
 * /fast_planner_node/search/lambda_heu: 5.0
 * /fast_planner_node/search/margin: 0.2
 * /fast_planner_node/search/max_acc: 2.0
 * /fast_planner_node/search/max_tau: 0.6
 * /fast_planner_node/search/max_vel: 3.0
 * /fast_planner_node/search/resolution_astar: 0.1
 * /fast_planner_node/search/time_resolution: 0.8
 * /fast_planner_node/search/w_time: 10.0
 * /gazebo/enable_ros_network: True
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/landing_target/camera/fov_x: 2.0071286398
 * /mavros/landing_target/camera/fov_y: 2.0071286398
 * /mavros/landing_target/image/height: 480
 * /mavros/landing_target/image/width: 640
 * /mavros/landing_target/land_target_type: VISION_FIDUCIAL
 * /mavros/landing_target/listen_lt: False
 * /mavros/landing_target/mav_frame: LOCAL_NED
 * /mavros/landing_target/target_size/x: 0.3
 * /mavros/landing_target/target_size/y: 0.3
 * /mavros/landing_target/tf/child_frame_id: camera_center
 * /mavros/landing_target/tf/frame_id: landing_target
 * /mavros/landing_target/tf/listen: False
 * /mavros/landing_target/tf/rate_limit: 10.0
 * /mavros/landing_target/tf/send: True
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: True
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mission/use_mission_item_int: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/fcu/odom_child_id_des: base_link
 * /mavros/odometry/fcu/odom_parent_id_des: map
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_raw/thrust_scaling: 1.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: odom
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /mavros/wheel_odometry/child_frame_id: base_link
 * /mavros/wheel_odometry/count: 2
 * /mavros/wheel_odometry/frame_id: odom
 * /mavros/wheel_odometry/send_raw: True
 * /mavros/wheel_odometry/send_twist: False
 * /mavros/wheel_odometry/tf/child_frame_id: base_link
 * /mavros/wheel_odometry/tf/frame_id: odom
 * /mavros/wheel_odometry/tf/send: False
 * /mavros/wheel_odometry/use_rpm: False
 * /mavros/wheel_odometry/vel_error: 0.1
 * /mavros/wheel_odometry/wheel0/radius: 0.05
 * /mavros/wheel_odometry/wheel0/x: 0.0
 * /mavros/wheel_odometry/wheel0/y: -0.15
 * /mavros/wheel_odometry/wheel1/radius: 0.05
 * /mavros/wheel_odometry/wheel1/x: 0.0
 * /mavros/wheel_odometry/wheel1/y: 0.15
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.12
 * /traj_server/traj_server/time_forward: 1.5
 * /use_gui: True
 * /use_sim_time: True
 * /waypoint_generator/waypoint_type: manual-lonely-way...

NODES
  /
    camera_link_base_link (tf/static_transform_publisher)
    fast_planner_node (plan_manage/fast_planner_node)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    mavros (mavros/mavros_node)
    robot_state_publisher (robot_state_publisher/state_publisher)
    rvizvisualisation (rviz/rviz)
    sitl (px4/px4)
    traj_msg_converter (plan_manage/trajectory_msg_converter_raw.py)
    traj_server (plan_manage/traj_server)
    vehicle_spawn_enord_32093_2826947510407897450 (gazebo_ros/spawn_model)
    waypoint_generator (waypoint_generator/waypoint_generator)

ROS_MASTER_URI=http://localhost:11311

process[fast_planner_node-1]: started with pid [32117]
process[traj_server-2]: started with pid [32118]
process[waypoint_generator-3]: started with pid [32120]
ERROR: cannot launch node of type [plan_manage/trajectory_msg_converter_raw.py]: Cannot locate node of type [trajectory_msg_converter_raw.py] in package [plan_manage]. Make sure file exists in package path and permission is set to executable (chmod +x)
process[rvizvisualisation-5]: started with pid [32209]
process[robot_state_publisher-6]: started with pid [32210]
[ WARN] [1634914760.374593207]: The 'state_publisher' executable is deprecated. Please use 'robot_state_publisher' instead
hit: 0.619039
miss: -0.619039
min log: -1.99243
max: 2.19722
thresh log: 1.38629
origin_: -20 -10  -1
map size: 40 20  5
process[sitl-7]: started with pid [399]
Creating symlink /home/enord/PX4-Autopilot/build/px4_sitl_default/etc -> /home/enord/.ros/etc

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
process[gazebo-8]: started with pid [450]
ERROR  [init] Unknown model iris_depth_camera (not found by name on /home/enord/.ros/etc/init.d-posix/airframes)
ERROR [px4] Startup script returned with return value: 256
process[gazebo_gui-9]: started with pid [469]
================================================================================REQUIRED process [sitl-7] has died!
process has died [pid 399, exit code 255, cmd /home/enord/PX4-Autopilot/build/px4_sitl_default/bin/px4 /home/enord/PX4-Autopilot/build/px4_sitl_default/etc -s etc/init.d-posix/rcS __name:=sitl __log:=/home/enord/.ros/log/85e76976-3346-11ec-96d8-706655b11773/sitl-7.log].
log file: /home/enord/.ros/log/85e76976-3346-11ec-96d8-706655b11773/sitl-7*.log
Initiating shutdown!
================================================================================
RLException: cannot add process [vehicle_spawn_enord_32093_2826947510407897450-10] after process monitor has been shut down
The traceback for the exception was written to the log file
[gazebo_gui-9] killing on exit
[gazebo-8] killing on exit
[sitl-7] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/catkin_find", line 12, in <module>
    from catkin.find_in_workspaces import find_in_workspaces  # noqa: E402
  File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/find_in_workspaces.py", line 39, in <module>
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/catkin_find", line 12, in <module>
    from catkin.find_in_workspaces import find_in_workspaces  # noqa: E402
  File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/find_in_workspaces.py", line 39, in <module>
[robot_state_publisher-6] killing on exit
        from catkin_pkg.packages import find_packages
from catkin_pkg.packages import find_packages
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 38, in <module>
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 38, in <module>
    from .package import _get_package_xml
      File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 43, in <module>
from .package import _get_package_xml
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 43, in <module>
    from catkin_pkg.condition import evaluate_condition
      File "/usr/lib/python2.7/dist-packages/catkin_pkg/condition.py", line 17, in <module>
from catkin_pkg.condition import evaluate_condition
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/condition.py", line 17, in <module>
    import pyparsing as pp
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 5377, in <module>
    import pyparsing as pp
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 5342, in <module>
[waypoint_generator-3] killing on exit
    class pyparsing_common:
      File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 5564, in pyparsing_common
anyOpenTag,anyCloseTag = makeHTMLTags(Word(alphas,alphanums+"_:").setName('any tag'))
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 2681, in __init__
    self.re = re.compile( self.reString )
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 572, in compile
    ipv6_address = Combine((_full_ipv6_address | _mixed_ipv6_address | _short_ipv6_address).setName("IPv6 address")).setName("IPv6 address")
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 4233, in __init__
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python2.7/sre_parse.py", line 735, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python2.7/sre_parse.py", line 343, in _parse_sub
    itemsappend(_parse(source, state, nested + 1))
  File "/usr/lib/python2.7/sre_parse.py", line 462, in _parse
    if this == "]" and set != start:
KeyboardInterrupt
    self.leaveWhitespace()
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 3725, in leaveWhitespace
    self.expr.leaveWhitespace()
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 3272, in leaveWhitespace
    e.leaveWhitespace()
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 3270, in leaveWhitespace
    self.exprs = [ e.copy() for e in self.exprs ]
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 3343, in copy
    ret.exprs = [e.copy() for e in self.exprs]
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 3343, in copy
    ret.exprs = [e.copy() for e in self.exprs]
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 3343, in copy
    ret.exprs = [e.copy() for e in self.exprs]
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 1160, in copy
    cpy = copy.copy( self )
  File "/usr/lib/python2.7/copy.py", line 88, in copy
    rv = reductor(2)
KeyboardInterrupt
[rvizvisualisation-5] killing on exit

**Comment by Cavalletta98** [comment]
Same problem, have you solved?
